// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJO6OxsAD7CQOI3lS3HXTFJZpm8rtQr6M',
    appId: '1:905385433219:web:626fe30c0eeb9d313d23b6',
    messagingSenderId: '905385433219',
    projectId: 'fir-flutter-consultorio',
    authDomain: 'fir-flutter-consultorio.firebaseapp.com',
    storageBucket: 'fir-flutter-consultorio.appspot.com',
    measurementId: 'G-XBS2T89CCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYr18dbVfNww3c90E4coLY7i7dEqGybjE',
    appId: '1:905385433219:android:61d4884d0ed204fe3d23b6',
    messagingSenderId: '905385433219',
    projectId: 'fir-flutter-consultorio',
    storageBucket: 'fir-flutter-consultorio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNl-n3sJnyNYd88tIIjelEm2V4cSoS7xs',
    appId: '1:905385433219:ios:682cebe7e031ea503d23b6',
    messagingSenderId: '905385433219',
    projectId: 'fir-flutter-consultorio',
    storageBucket: 'fir-flutter-consultorio.appspot.com',
    iosClientId: '905385433219-gl34o2udlriof0seq84n6ekrrvef2uh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNl-n3sJnyNYd88tIIjelEm2V4cSoS7xs',
    appId: '1:905385433219:ios:682cebe7e031ea503d23b6',
    messagingSenderId: '905385433219',
    projectId: 'fir-flutter-consultorio',
    storageBucket: 'fir-flutter-consultorio.appspot.com',
    iosClientId: '905385433219-gl34o2udlriof0seq84n6ekrrvef2uh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
